// Generated by CoffeeScript 2.2.1
(function() {
  'use strict';
  var CND, alert, badge, config, debug, help, info, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERSHOP/MAIN';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  config = require('config');

  info(config);

  info(config.get('app'));

  info(config.get('db'));

}).call(this);

//# sourceMappingURL=main.js.map
