#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'


# pg_stat_activity
# pg_stat_all_indexes
# pg_stat_all_tables
# pg_stat_archiver
# pg_stat_bgwriter
# pg_stat_database
# pg_stat_database_conflicts
# pg_stat_progress_vacuum
# pg_stat_replication
# pg_stat_ssl
# pg_stat_sys_indexes
# pg_stat_sys_tables
# pg_stat_user_functions
# pg_stat_user_indexes
# pg_stat_user_tables
# pg_stat_wal_receiver
# pg_stat_xact_all_tables
# pg_stat_xact_sys_tables
# pg_stat_xact_user_functions
# pg_stat_xact_user_tables
# pg_statio_all_indexes
# pg_statio_all_sequences
# pg_statio_all_tables
# pg_statio_sys_indexes
# pg_statio_sys_sequences
# pg_statio_sys_tables
# pg_statio_user_indexes
# pg_statio_user_sequences
# pg_statio_user_tables
# pg_statistic
# pg_stats


intershop_host_path=$(pwd)
# home=$(realpath "$(readlink -f "$0" | xargs dirname)"/..)
home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/..)"
cd "$home"
source bin/_prepare-environment
# sudo_postgres_unpaged "$intershop_db_name" -f views/active-queries.sql
# declare -g sudo_postgres_unpaged
# declare -x sudo_postgres_unpaged
# export sudo_postgres_unpaged

# watch -n 0.1 -d 'sudo -u postgres bin/itsql --pset="pager=off" -f views/active-queries.sql'
# watch -n 0.1 -d 'sudo -u postgres bin/itsql --pset="pager=off" -f views/active-queries.sql'
# watch -n 0.1 -d 'sudo_postgres_unpaged '"$intershop_db_name"' -f views/active-queries.sql'

# watch -n 0.1 -d "sudo -u postgres psql -d intershop --set QUIET=on --set ON_ERROR_STOP=1 -f views/active-queries.sql"
watch -n 0.1 -d "sudo -u postgres psql -p $intershop_db_port -d $intershop_db_name --set QUIET=on --set ON_ERROR_STOP=1 -f views/active-queries.sql"



