// Generated by CoffeeScript 2.0.3
(function() {
  var FS;

  FS = require('fs');

  //-----------------------------------------------------------------------------------------------------------
  this.split_line = function(line) {
    var path, type, value;
    [path, type, value] = line.trim().split(/\s+/, 3);
    return {path, type, value};
  };

  //-----------------------------------------------------------------------------------------------------------
  this.hash_from_path = function(path) {
    return this.update_hash_from_path(path, {});
  };

  //-----------------------------------------------------------------------------------------------------------
  this.update_hash_from_path = function(path, R) {
    var i, len, line, ref, source, type, value;
    source = FS.readFileSync(path, {
      encoding: 'utf-8'
    });
    ref = source.split('\n');
    for (i = 0, len = ref.length; i < len; i++) {
      line = ref[i];
      if ((line.match(/^\s*$/)) != null) {
        continue;
      }
      if ((line.match(/^\s*#/)) != null) {
        continue;
      }
      ({path, type, value} = split_line(line));
      R[parts.path] = {type, value};
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.options_as_facet_json = function(x) {
    return JSON.stringify(x);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.options_as_untyped_json = function(x) {
    var R, facet, key;
    R = {};
    for (key in x) {
      facet = x[key];
      R[key] = facet.value;
    }
    return JSON.stringify(R);
  };

}).call(this);

//# sourceMappingURL=ptv-reader.js.map
